// auth //
export const SIGNUP_USER = 'SIGNUP_USER'
export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'

// modal //
export const CLOSE_MODAL = 'CLOSE_MODAL'
export const OPEN_AUTH_MODAL = 'OPEN_AUTH_MODAL'
export const OPEN_ADD_TASK_MODAL = 'OPEN_ADD_TASK_MODAL'
export const CLOSE_ADD_TASK_MODAL = 'CLOSE_ADD_TASK_MODAL'
export const OPEN_ADD_ACC_MODAL = 'OPEN_ADD_ACC_MODAL'
export const CLOSE_ADD_ACC_MODAL = 'CLOSE_ADD_ACC_MODAL'

// goal //
export const GET_ALL_GOAL = 'GET_ALL_GOAL';
export const GET_GOAL = 'GET_GOAL'
export const ADD_GOAL = 'ADD_GOAL'
export const EDIT_GOAL = 'EDIT_GOAL'
export const DELETE_GOAL = 'DELETE_GOAL'
export const ADD_TASK_TO_GOAL = 'ADD_TASK_TO_GOAL'
export const DELETE_TASK_FROM_GOAL = 'DELETE_TASK_FROM_GOAL'

// task //
export const GET_ALL_TASK = 'GET_ALL_TASK'
export const ADD_TASK = 'ADD_TASK'
export const DELETE_TASK = 'DELETE_TASK'
export const EDIT_TASK = 'EDIT_TASK'
export const EDIT_TASK_OF_ACHIEVEMENT = 'EDIT_TASK_OF_ACHIEVEMENT'

// achievement //
export const GET_ACHIEVEMENTS_OF_TASK = 'GET_ACHIEVEMENTS_OF_TASK'
export const GET_ACHIEVEMENTS_OF_GOAL = 'GET_ACHIEVEMENTS_OF_GOAL'
export const ADD_ACHIEVEMENT = 'ADD_ACHIEVEMENT'
export const EDIT_ACHIEVEMENT = 'EDIT_ACHIEVEMENT'
export const DELETE_ACHIEVEMENT = 'DELETE_ACHIEVEMENT'

// explore //
export const EXPLORE_GET_ALL_GOAL = 'EXPLORE_GET_ALL_GOAL'
export const EXPLORE_GET_GOAL = 'EXPLORE_GET_GOAL'
export const EXPLORE_GET_ACH_BY_GOAL = 'EXPLORE_GET_ACH_BY_GOAL'