# Generated by Django 3.1.2 on 2020-11-04 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='recurrent',
        ),
    ]
