# Generated by Django 3.1.2 on 2020-11-11 12:38

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20201111_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='day_of_week',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=56),
        ),
    ]
