# Generated by Django 3.1.2 on 2020-11-05 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_goal_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='image',
        ),
    ]
