# Generated by Django 3.1.2 on 2020-11-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0009_auto_20201111_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='photo',
            field=models.URLField(blank=True, max_length=2047, null=True),
        ),
    ]
