# Generated by Django 3.1.2 on 2020-11-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0010_auto_20201117_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
