# Generated by Django 3.1.2 on 2020-12-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='title',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
