# Generated by Django 3.1.2 on 2020-11-20 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='pecentage_complete',
            new_name='percentage_complete',
        ),
    ]
