# Generated by Django 3.1.2 on 2020-11-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_auto_20201120_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='written_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='percentage_complete',
            field=models.IntegerField(default=0),
        ),
    ]
