# Generated by Django 3.1.2 on 2020-11-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0004_auto_20201130_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='percentage_complete',
            field=models.IntegerField(default=0),
        ),
    ]
